name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: devops-repo-owner/devops-repo-name/steps/build_action.yml@main
        with:
          tags: ${{ inputs.tags }}
          build-args: ${{ inputs.build-args }}

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker Image
        uses: devops-repo-owner/devops-repo-name/steps/push_action.yml@main
        with:
          tags: ${{ inputs.tags }}
