name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: ./.github/actions/steps/build
        with:
          tags: ${{ inputs.tags }}

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker Image
        uses: ./.github/actions/steps/push
        with:
          tags: ${{ inputs.tags }}
